import {
  DashboardOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  UserOutlined,
  PictureOutlined,
  GiftOutlined,
  ShopOutlined,
  UsergroupAddOutlined,
  MailOutlined,
  SettingOutlined,
  MobileOutlined,
  FileTextOutlined,
} from '@ant-design/icons';

import { APP_PREFIX_PATH } from 'configs/AppConfig';

const dashBoardNavTree = [
  {
    key: 'dashboards',
    path: `${APP_PREFIX_PATH}/dashboards`,
    title: 'sidenav.dashboard.basic',
    icon: DashboardOutlined,
    breadcrumb: false,
    isGroupTitle: true,
    submenu: [],
  },
  {
    key: 'dashboards-default',
    path: `${APP_PREFIX_PATH}/dashboards/default`,
    title: 'sidenav.dashboard',
    icon: DashboardOutlined,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'dashboards-catalog',
    path: `${APP_PREFIX_PATH}/dashboards/catalog`,
    title: 'sidenav.dashboard.catalog',
    icon: ShoppingCartOutlined,
    isGroupTitle: false,
    breadcrumb: false,
    submenu: [
      {
        key: 'dashboards-catalog-products',
        path: `${APP_PREFIX_PATH}/dashboards/catalog/products`,
        title: 'sidenav.dashboard.catalog.products',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
      {
        key: 'dashboards-catalog-categories',
        path: `${APP_PREFIX_PATH}/dashboards/catalog/categories`,
        title: 'sidenav.dashboard.catalog.categories',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
      {
        key: 'dashboards-catalog-collections',
        path: `${APP_PREFIX_PATH}/dashboards/catalog/collections`,
        title: 'sidenav.dashboard.catalog.collections',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
      {
        key: 'dashboards-catalog-combo',
        path: `${APP_PREFIX_PATH}/dashboards/catalog/combo`,
        title: 'sidenav.dashboard.catalog.combo',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
  {
    key: 'dashboards-orders',
    path: `${APP_PREFIX_PATH}/dashboards/orders`,
    title: 'sidenav.dashboard.orders',
    icon: ShoppingOutlined,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'dashboards-сustomers',
    path: `${APP_PREFIX_PATH}/dashboards/сustomers`,
    title: 'sidenav.dashboard.сustomers',
    icon: UserOutlined,
    breadcrumb: false,
    isGroupTitle: false,
    breadcrumb: false,
    submenu: [
      {
        key: 'dashboards-customers-customersList',
        path: `${APP_PREFIX_PATH}/dashboards/customers/list`,
        title: 'sidenav.dashboard.customers.customersList',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
      {
        key: 'dashboards-customers-customersGroup',
        path: `${APP_PREFIX_PATH}/dashboards/customers/group`,
        title: 'sidenav.dashboard.customers.customersGroup',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
  {
    key: 'dashboards-banners',
    path: `${APP_PREFIX_PATH}/dashboards/banners`,
    title: 'sidenav.dashboard.banners',
    icon: PictureOutlined,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'dashboards-promocodes',
    path: `${APP_PREFIX_PATH}/dashboards/promocodes`,
    title: 'sidenav.dashboard.promocodes',
    icon: GiftOutlined,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'dashboards-offlinePoints',
    path: `${APP_PREFIX_PATH}/dashboards/offlinePoints`,
    title: 'sidenav.dashboard.offlinePoints',
    icon: ShopOutlined,
    breadcrumb: false,
    submenu: [
      {
        key: 'dashboards-offlinePoints-offlinePointsAddress',
        path: `${APP_PREFIX_PATH}/dashboards/offlinePoints/address`,
        title: 'sidenav.dashboard.offlinePoints.offlinePointsAddress',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
      {
        key: 'dashboards-offlinePoints-offlinePointsGeofences',
        path: `${APP_PREFIX_PATH}/dashboards/offlinePoints/geofences`,
        title: 'sidenav.dashboard.offlinePoints.offlinePointsGeofences',
        icon: '',
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
  {
    key: 'dashboards-staff',
    path: `${APP_PREFIX_PATH}/dashboards/staff`,
    title: 'sidenav.dashboard.staff',
    icon: UsergroupAddOutlined,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'dashboards-mailing',
    path: `${APP_PREFIX_PATH}/dashboards/mailing`,
    title: 'sidenav.dashboard.mailing',
    icon: MailOutlined,
    breadcrumb: false,
    submenu: [],
  },

  {
    key: 'system',
    path: `${APP_PREFIX_PATH}/system`,
    title: 'sidenav.system',
    icon: DashboardOutlined,
    breadcrumb: false,
    isGroupTitle: true,
    submenu: [],
  },
  {
    key: 'system-settings',
    path: `${APP_PREFIX_PATH}/system/settings`,
    title: 'sidenav.system.settings',
    icon: SettingOutlined,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'system-mobileApp',
    path: `${APP_PREFIX_PATH}/system/mobileApp`,
    title: 'sidenav.system.mobileApp',
    icon: MobileOutlined,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'system-logs',
    path: `${APP_PREFIX_PATH}/system/logs`,
    title: 'sidenav.system.logs',
    icon: FileTextOutlined,
    breadcrumb: false,
    submenu: [],
  },
];

const navigationConfig = [...dashBoardNavTree];

export default navigationConfig;
